### ISSUE TITLE
Hal silently deactivates the lock when switching parameters

### ISSUE THREAD

**Issue by AlistairBoettiger** [ZhuangLab/storm-control#114]
In the current version of storm-control, a bug has been recently introduced such that when Dave tells Hal to switch parameters, the lock is silently inactivated.  I call this 'silent' as the Locked/Unlocked button text still reads "Locked", but the behavior is definitely that of the unlocked system.  If the user pauses Dave and just double clicks the Lock to unlock/lock the lock behavior is restored until Hal requests a parameter change again. 
I've written a work around that to add a Dave Action that switches the lock off and on, which we can call after reach parameter switch, but I haven't found the source of the bug that stops the lock on switching parameters.

**Comment by BoettigerLab** [comment]
It turns out this bug resulted from a silent merge conflict. If I test the same system on a clean copy of master rather than the merge of master, the lock behaves as expected (which I should have tested before posting).  We can close this issue.
