### ISSUE TITLE
Automated imaging optimizations

### ISSUE THREAD

**Issue by HazenBabcock** [ZhuangLab/storm-control#17]
The acquisition of images in automated mode (i.e. under Dave or Steve control) could be faster.

**Comment by jeffmoffitt** [comment]
Cameras should check to see what parameters are different from the current configuration and only change those.  Also, the camera should control whether or not it needs to be stopped during this change, not hal.

**Comment by HazenBabcock** [comment]
The cameras themselves now decide if they need to stop/start. I believe that Python3 / PyQt5 HAL is faster. Closing this issue because it is basically open-ended.
