### ISSUE TITLE
kilroy - missing imports

### ISSUE THREAD

**Issue by BogdanBintu** [ZhuangLab/storm-control#42]
Since Hazen added a set path file in python I would suggest using it otherwise I experienced trouble with the "serial" module.

Suggested fix:
In **kilroy.py** suggest adding:
import imp
imp.load_source("setPath", "../sc_library/setPath.py")

**Comment by HazenBabcock** [comment]
I would suggest using Python [virtual environments](http://docs.python-guide.org/en/latest/dev/virtualenvs/) instead. It is quite easy to do and it is the right way to solve this problem. You can make it automatic by adding the venv activation step to your .bat files.
