### ISSUE TITLE
Hal Andor class cannot find some driver paths

### ISSUE THREAD

**Issue by BogdanBintu** [ZhuangLab/storm-control#52]
The 
initCamera(self, pci_card = 0) 
function in class 
ACameraControl(cameraControl.HWCameraControl)
in file 
storm-control/hal4000/camera/andorCameraControl.py
has hardcoded in the paths to the Andor dll drivers.
The new: "C:\Program Files\Andor Driver Pack 2" path is missing from the list.
I recommend adding this as a camera parameter.

**Comment by HazenBabcock** [comment]
Fixed.
